const stages=[
{title:"Developer & Source Control",phase:"Commit",icon:"</>",accent:"#4d8ff7",short:"Application, Terraform, or Kubernetes changes enter through a reviewed Git workflow.",tags:[["GitHub","Hosted Git repository and pull requests"],["GitLab","Source control and merge requests"]],points:["Push application, infrastructure, or Kubernetes changes.","Pull or merge requests trigger automated pipelines.","Protected branches keep reviewed code as the release source."]},
{title:"CI Validation",phase:"Test",icon:"✓",accent:"#4d8ff7",short:"Fast validation rejects broken code and invalid infrastructure definitions.",tags:[["Python","Application unit tests"],["Terraform","Infrastructure formatting and validation"],["Helm","Kubernetes package linting"],["Jenkins","Self-managed pipeline orchestration"]],points:["Run Python unit tests.","Check Terraform formatting and validate configuration.","Lint and render the Helm chart.","Execute with Jenkins, GitHub Actions, or GitLab CI."]},
{title:"DevSecOps Security Gates",phase:"Scan",icon:"◆",accent:"#39d98a",short:"Layered policy and vulnerability checks stop unsafe artifacts before publication.",tags:[["SonarQube","Static code quality analysis"],["OWASP","Dependency vulnerability detection"],["Snyk","Open-source dependency scanning"],["Checkov","Terraform and Kubernetes policy scanning"],["Trivy","Container vulnerability scanner"]],points:["Apply the SonarQube quality gate.","Scan dependencies with OWASP Dependency-Check and Snyk.","Scan Terraform and Kubernetes configuration with Checkov.","Fail on defined critical or high-severity findings."]},
{title:"Container Build & Registry",phase:"Build / ECR",icon:"▣",accent:"#ff9900",short:"A non-root image is versioned, scanned, and published with temporary AWS credentials.",tags:[["Docker","OCI image build"],["Amazon ECR","Private container registry"],["AWS KMS","Registry encryption"],["OIDC","Short-lived cloud authentication"]],points:["Build a non-root container image.","Tag with the commit SHA or release version.","Exchange CI identity for temporary AWS credentials through OIDC.","Push the approved image to KMS-encrypted Amazon ECR."]},
{title:"GitOps Promotion",phase:"GitOps",icon:"↻",accent:"#a982ff",short:"The desired image version moves through reviewed environment-specific Git configuration.",tags:[["Git","Auditable desired-state history"],["Helm values","Environment-specific release configuration"]],points:["Update the image tag in the target environment values file.","Keep development and production Helm values separate.","Review production promotion as a Git change.","Use Git as the single source of truth."]},
{title:"Argo CD Deployment",phase:"Argo CD",icon:"◎",accent:"#a982ff",short:"Argo CD reconciles the reviewed Helm state while admission policy protects the cluster.",tags:[["Argo CD","GitOps reconciliation controller"],["Helm","Kubernetes release templates"],["Gatekeeper","OPA admission policies"]],points:["Detect and synchronize the GitOps repository change.","Prune stale resources and self-heal configuration drift.","Evaluate health and retain revision history for rollback.","Validate resources through OPA Gatekeeper before admission."]},
{title:"Amazon EKS Runtime",phase:"EKS",icon:"☸",accent:"#4d8ff7",short:"Private EKS capacity runs hardened workloads with independent pod and node scaling.",tags:[["Amazon EKS","Managed Kubernetes control plane"],["HPA","Pod autoscaling"],["Karpenter","Just-in-time EC2 provisioning"],["External Secrets","Kubernetes secret synchronization"]],points:["Run workloads on private worker nodes.","Scale pods with HPA and nodes with Karpenter.","Apply probes, limits, NetworkPolicy, PDB, IRSA, and Pod Identity.","Retrieve secrets from AWS Secrets Manager through External Secrets."]},
{title:"Monitoring & Operations",phase:"Monitor",icon:"⌁",accent:"#39d98a",short:"Metrics, alerts, events, and deployment state provide continuous operational feedback.",tags:[["Prometheus","Metrics collection and rules"],["Grafana","Operational dashboards"],["Alertmanager","Alert routing"]],points:["Collect application and cluster metrics with Prometheus.","Visualize release and runtime health in Grafana.","Route actionable alerts through Alertmanager.","Troubleshoot with logs, metrics, Kubernetes events, and Argo CD status."]},
{title:"Rollback",phase:"Recover",icon:"↶",accent:"#ff5f69",short:"Git and Argo CD revision history restore the last known-good application state.",tags:[["Git revert","Auditable desired-state rollback"],["Argo CD","Revision selection and reconciliation"]],points:["Revert the failed image-tag commit or choose a previous Argo CD revision.","Synchronize the last known-good Helm configuration.","Verify restored workload health and monitoring signals."]}
];
const pipeline=document.querySelector("#pipeline"),panel=document.querySelector("#detailPanel"),backdrop=document.querySelector("#backdrop"),closeButton=document.querySelector("#closePanel"),runButton=document.querySelector("#runWorkflow"),resetButton=document.querySelector("#resetWorkflow"),progress=document.querySelector("#progressBar"),statusText=document.querySelector("#runStatus");let timer=null,lastFocus=null;
const tagMarkup=tags=>tags.map(([name,tip])=>`<span class="tech-tag" tabindex="0" data-tooltip="${tip}">${name}</span>`).join("");
stages.forEach((stage,index)=>{const card=document.createElement("button");card.type="button";card.className="stage-card";card.style.setProperty("--accent",stage.accent);card.dataset.index=index;card.innerHTML=`<span class="stage-top"><span class="stage-number">${String(index+1).padStart(2,"0")}</span><span class="stage-state">Waiting</span></span><span class="stage-icon" aria-hidden="true">${stage.icon}</span><h3>${stage.title}</h3><p>${stage.short}</p><span class="tag-list">${tagMarkup(stage.tags)}</span>`;card.addEventListener("click",event=>{if(event.target.classList.contains("tech-tag"))return;openDetails(index,card)});pipeline.append(card)});
const cards=[...document.querySelectorAll(".stage-card")];
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("revealed");observer.unobserve(entry.target)}}),{threshold:.15});cards.forEach(card=>observer.observe(card));
function openDetails(index,trigger){const stage=stages[index];lastFocus=trigger;cards.forEach(c=>c.classList.remove("selected"));trigger.classList.add("selected");document.querySelector("#detailNumber").textContent=`STAGE ${String(index+1).padStart(2,"0")}`;document.querySelector("#detailIcon").textContent=stage.icon;document.querySelector("#detailPhase").textContent=stage.phase;document.querySelector("#detailTitle").textContent=stage.title;document.querySelector("#detailDescription").textContent=stage.short;document.querySelector("#detailPoints").innerHTML=stage.points.map(point=>`<li>${point}</li>`).join("");document.querySelector("#detailTags").innerHTML=stage.tags.map(([name])=>`<span>${name}</span>`).join("");panel.classList.add("open");panel.setAttribute("aria-hidden","false");backdrop.hidden=false;document.body.style.overflow="hidden";closeButton.focus()}
function closeDetails(){panel.classList.remove("open");panel.setAttribute("aria-hidden","true");backdrop.hidden=true;document.body.style.overflow="";cards.forEach(c=>c.classList.remove("selected"));lastFocus?.focus()}
function resetWorkflow(announce=true){clearInterval(timer);timer=null;cards.forEach(card=>{card.classList.remove("running","passed","failed");card.querySelector(".stage-state").textContent="Waiting"});progress.style.width="0";runButton.disabled=false;if(announce)statusText.textContent="Ready · choose an outcome and run the workflow"}
function runWorkflow(){resetWorkflow(false);const failure=document.querySelector('input[name="outcome"]:checked').value==="failure";const stopIndex=failure?2:cards.length-1;let index=0;runButton.disabled=true;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const advance=()=>{cards.forEach(card=>card.classList.remove("running"));const card=cards[index];card.classList.add("running");card.querySelector(".stage-state").textContent="Active";statusText.textContent=`${stages[index].phase} · ${stages[index].title}`;progress.style.width=`${((index+1)/cards.length)*100}%`;setTimeout(()=>{card.classList.remove("running");if(failure&&index===stopIndex){card.classList.add("failed");card.querySelector(".stage-state").textContent="Failed";statusText.textContent="Pipeline stopped · critical security gate failed before image publishing";runButton.disabled=false;clearInterval(timer);timer=null}else{card.classList.add("passed");card.querySelector(".stage-state").textContent="Passed";if(index===stopIndex){statusText.textContent="Deployment healthy · monitoring active and rollback ready";runButton.disabled=false;clearInterval(timer);timer=null}}index++},reduced?0:420)};advance();timer=setInterval(advance,reduced?80:760)}
runButton.addEventListener("click",runWorkflow);resetButton.addEventListener("click",()=>resetWorkflow());closeButton.addEventListener("click",closeDetails);backdrop.addEventListener("click",closeDetails);document.addEventListener("keydown",event=>{if(event.key==="Escape"&&panel.classList.contains("open"))closeDetails()});
