const components={
"Kubernetes Cluster":["K8S","Hosts the workloads and infrastructure targets observed by the platform.","Origin of node, pod, workload, and control-plane signals.","Investigate a deployment whose pods are pending after a node capacity change."],
"Node Exporter":["NODE","Exposes operating-system and hardware metrics from every Kubernetes node.","DaemonSet target scraped by Prometheus in the metrics pipeline.","Alert when node filesystem space or available memory crosses a safe threshold."],
"kube-state-metrics":["KSM","Converts Kubernetes object state into Prometheus metrics.","Provides deployment, pod, job, and resource status after the cluster source.","Detect unavailable replicas or pods stuck in a non-running phase."],
"Metrics Server":["MS","Provides recent resource usage for Kubernetes autoscaling and kubectl top.","Supplies lightweight CPU and memory data beside the Prometheus stack.","Validate HPA input and quickly inspect a high-CPU pod."],
"Prometheus":["PROM","Scrapes, stores, and evaluates time-series metrics and alert rules.","Central metrics engine between exporters and Grafana or Alertmanager.","Calculate pod saturation and fire an alert after a sustained threshold breach."],
"Grafana":["GRAF","Provides dashboards and investigation across metrics, logs, and traces.","Shared visualization destination for the three telemetry pipelines.","Correlate a latency spike with pod restarts, logs, and a trace waterfall."],
"Kubernetes Pods & Nodes":["PODS","Generate container logs and Kubernetes metadata on each worker node.","Source of the centralized logging pipeline.","Capture an application error together with namespace, pod, and container labels."],
"Fluent Bit":["FB","Tails container logs, enriches records with Kubernetes metadata, and forwards them.","Node-level log collector between workloads and Loki.","Parse JSON application logs and remove noisy fields before storage."],
"Loki":["LOKI","Indexes log labels and stores compressed log streams for efficient queries.","Central log backend queried through Grafana.","Search all error logs for a release label during an incident."],
"Applications":["APP","Emit spans that describe requests across service boundaries.","Source of the distributed tracing pipeline.","Trace a slow checkout request across API, cache, and database calls."],
"OTLP":["OTLP","Standard protocol used to export telemetry from instrumented applications.","Transport boundary between applications and Tempo.","Send HTTP or gRPC spans without coupling the service to a storage vendor."],
"Tempo":["TEMPO","Stores distributed traces and returns trace data by identifier.","Trace backend integrated with Grafana and correlated telemetry.","Open a trace ID found in a Loki log to inspect the request path."],
"Prometheus Alert Rules":["RULE","Evaluate metric expressions into pending and firing alert states.","Start of the alerting pipeline inside Prometheus.","Fire a HighPodRestartRate alert only after the condition persists for ten minutes."],
"Alertmanager":["AM","Groups, deduplicates, silences, and routes firing alerts.","Policy and routing layer between Prometheus and notification channels.","Group alerts by cluster and namespace, then route critical production events."],
"Slack Alerts":["SLACK","Deliver concise real-time alert notifications to operational channels.","Immediate collaborative destination from Alertmanager.","Notify the on-call channel with severity, summary, dashboard, and runbook links."],
"Email Alerts":["MAIL","Deliver durable alert notifications and summaries to defined receivers.","Auditable notification destination from Alertmanager.","Send platform-capacity alerts to the infrastructure distribution list."]};
const lanes=[
{id:"metrics",title:"Metrics Pipeline",color:"#35c4dd",nodes:[["Kubernetes Cluster"],["Node Exporter","kube-state-metrics","Metrics Server"],["Prometheus"],["Grafana"]]},
{id:"logs",title:"Logs Pipeline",color:"#3bd18b",nodes:[["Kubernetes Pods & Nodes"],["Fluent Bit"],["Loki"],["Grafana"]]},
{id:"traces",title:"Traces Pipeline",color:"#9a86f7",nodes:[["Applications"],["OTLP"],["Tempo"],["Grafana"]]},
{id:"alerts",title:"Alerts Pipeline",color:"#f4b84a",nodes:[["Prometheus Alert Rules"],["Alertmanager"],["Slack Alerts","Email Alerts"]]}
];
const laneRoot=document.querySelector("#lanes"),drawer=document.querySelector("#drawer"),backdrop=document.querySelector("#backdrop"),closeButton=document.querySelector("#closeDrawer");let lastFocus=null;
lanes.forEach(lane=>{const section=document.createElement("section");section.className="lane";section.dataset.lane=lane.id;section.style.setProperty("--lane-color",lane.color);const groups=lane.nodes.map(group=>{const buttons=group.map(name=>`<button class="node" type="button" data-component="${name}" data-lane="${lane.title}"><span class="node-icon">${components[name][0]}</span><strong>${name}</strong><small>View component details</small></button>`).join("");return group.length>1?`<div class="node-group">${buttons}</div>`:buttons}).join("");section.innerHTML=`<div class="lane-title"><span>${lane.id}</span><h3>${lane.title}</h3></div><div class="node-flow">${groups}</div>`;laneRoot.append(section)});
document.querySelectorAll(".node").forEach(node=>node.addEventListener("click",()=>openDrawer(node)));
function openDrawer(node){const [icon,purpose,position,example]=components[node.dataset.component];lastFocus=node;document.querySelectorAll(".node").forEach(item=>item.classList.toggle("selected",item===node));document.querySelector("#drawerLane").textContent=node.dataset.lane.toUpperCase();document.querySelector("#drawerIcon").textContent=icon;document.querySelector("#drawerTitle").textContent=node.dataset.component;document.querySelector("#drawerPurpose").textContent=purpose;document.querySelector("#drawerPosition").textContent=position;document.querySelector("#drawerExample").textContent=example;drawer.classList.add("open");drawer.scrollTop=0;drawer.setAttribute("aria-hidden","false");backdrop.hidden=false;document.body.style.overflow="hidden";closeButton.focus({preventScroll:true})}
function closeDrawer(){drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true");backdrop.hidden=true;document.body.style.overflow="";document.querySelectorAll(".node").forEach(node=>node.classList.remove("selected"));lastFocus?.focus()}
document.querySelectorAll(".filters button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".filters button").forEach(item=>{const active=item===button;item.classList.toggle("active",active);item.setAttribute("aria-pressed",String(active))});document.querySelectorAll(".lane").forEach(lane=>lane.classList.toggle("filtered",button.dataset.filter!=="all"&&lane.dataset.lane!==button.dataset.filter))}));
closeButton.addEventListener("click",closeDrawer);backdrop.addEventListener("click",closeDrawer);document.addEventListener("keydown",event=>{if(event.key==="Escape"&&drawer.classList.contains("open"))closeDrawer()});
