// A single data source drives both workflow cards and the contextual details panel.
const workflowSteps=[
{name:"Push code to GitHub",description:"A reviewed application or deployment change is pushed to the project repository and starts the delivery process.",tool:"GitHub",status:"Source",icon:"</>",output:"Commit SHA, branch context, and webhook event"},
{name:"Start Jenkins pipeline",description:"Jenkins checks out the exact revision and creates a traceable pipeline run for validation, build, scan, and deployment.",tool:"Jenkins",status:"CI",icon:"J",output:"Build number, workspace, console log, and stage timeline"},
{name:"Validate Docker Compose",description:"The pipeline validates the multi-service Compose definition before attempting local orchestration or image builds.",tool:"Docker Compose",status:"Validate",icon:"DC",output:"Validated compose.yaml and resolved service configuration"},
{name:"Build application images",description:"Separate nginx frontend and FastAPI backend images are built and tagged with the release identifier.",tool:"Docker / BuildKit",status:"Build",icon:"▣",output:"Frontend and backend image IDs, sizes, and SHA tags"},
{name:"Execute backend tests",description:"Automated FastAPI tests verify health endpoints, task operations, database behavior, and Redis integration.",tool:"Python test runner",status:"Test",icon:"✓",output:"Test report, pass/fail result, and coverage evidence"},
{name:"Run code quality scan",description:"SonarQube analyzes reliability, maintainability, duplication, coverage, and security hotspots before publication.",tool:"SonarQube",status:"Scan",icon:"◎",output:"Quality gate result and static-analysis dashboard"},
{name:"Publish Docker images",description:"Approved versioned images are authenticated and pushed to Docker Hub or a private Amazon ECR repository.",tool:"Docker Hub / AWS ECR",status:"Push",icon:"☁",output:"Registry image URIs, tags, and immutable digests"},
{name:"Deploy with Helm",description:"Helm renders environment values and deploys the release to Kubernetes or Amazon EKS with repeatable configuration.",tool:"Helm / Kubernetes",status:"Deploy",icon:"☸",output:"Helm revision, release status, and Kubernetes resources"},
{name:"Run microservices",description:"Kubernetes runs the nginx frontend, FastAPI backend, PostgreSQL database, and Redis cache as coordinated services.",tool:"Kubernetes / AWS EKS",status:"Runtime",icon:"K8S",output:"Ready pods, service endpoints, ingress, and health status"},
{name:"Collect deployment evidence",description:"The pipeline captures runtime state and diagnostic output to make the portfolio deployment verifiable and reproducible.",tool:"Jenkins / kubectl / Docker",status:"Verify",icon:"≡",output:"Containers, images, pods, services, logs, events, and health response"}
];
const grid=document.querySelector("#stepGrid"),cards=[];
workflowSteps.forEach((step,index)=>{const card=document.createElement("button");card.type="button";card.className="step-card";card.innerHTML=`<span class="step-number">${String(index+1).padStart(2,"0")}</span><span class="step-copy"><h3>${step.name}</h3><p>${step.description}</p><span class="step-footer"><span class="tool">${step.tool}</span><span class="status">${step.status}</span></span></span>`;card.style.setProperty("--accent",["#39c6e8","#ffbd59","#39c6e8","#498cf2","#42d38b","#39c6e8","#ffbd59","#498cf2","#42d38b","#39c6e8"][index]);card.addEventListener("click",()=>selectStep(index));grid.append(card);cards.push(card)});
function selectStep(index){const step=workflowSteps[index];cards.forEach((card,i)=>card.classList.toggle("selected",i===index));document.querySelector("#detailStatus").textContent=step.status;document.querySelector("#detailIcon").textContent=step.icon;document.querySelector("#detailTitle").textContent=step.name;document.querySelector("#detailDescription").textContent=step.description;document.querySelector("#detailTool").textContent=step.tool;document.querySelector("#detailOutput").textContent=step.output}
function resetSelection(){cards.forEach(card=>card.classList.remove("selected"));document.querySelector("#detailStatus").textContent="SELECT A STEP";document.querySelector("#detailIcon").textContent="i";document.querySelector("#detailTitle").textContent="Pipeline details";document.querySelector("#detailDescription").textContent="Select any workflow card to view the tool, action, and evidence generated at that stage.";document.querySelector("#detailTool").textContent="—";document.querySelector("#detailOutput").textContent="—";cards[0]?.focus()}
document.querySelector("#resetSelection").addEventListener("click",resetSelection);
